#!/bin/bash

set -euo

rm -rf dist
mkdir dist
cp src/phelipe-teles-resume-pt-br.json dist
cp src/phelipe-teles-resume-en-us.json dist
npm run build:pdf
npm run build:html
echo "Files in ./dist folder"
ls -l dist
npm run build:index
