name: Build Resumé and release

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Resumés
        uses: xu-cheng/texlive-action@v3
        with:
          texlive_version: latest
          os: alpine
          scheme: small
          run: |
            apk update
            apk add nodejs-lts npm
            npm run build
            tlmgr install scheme-basic geometry inputenc babel hyperref parskip newpx fontenc titlesec fontawesome5 tabularx enumitem csquotes babel-portuges xcolor xpatch xkeyval xstring fontaxes newtx textcomp

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
