name: Build Resumé and release

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Build Resumés
        uses: xu-cheng/texlive-action@v3
        with:
          texlive_version: latest
          os: alpine
          scheme: small
          run: |
            apk update
            apk add nodejs-lts npm
            tlmgr install newpx titlesec fontawesome5 enumitem csquotes xstring fontaxes newtx
            npm ci
            npm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
